" let g:neovide_cursor_vfx_mode = "railgun"
" set guifont=RictyDiminished\ Nerd\ Font:h20
set guifont=FiraCode\ Nerd\ Font:h15
" let g:neovide_fullscreen=v:true
let g:neovide_cursor_animation_length=0.08
let g:neovide_cursor_trail_length=0.02
"let g:neovide_cursor_antialiasing=v:true
let g:neovide_cursor_vfx_mode = "pixiedust"
let g:neovide_cursor_vfx_particle_lifetime=15
let g:neovide_cursor_vfx_particle_density=100.0
let g:neovide_cursor_vfx_particle_speed=5.0
