require('genF.init')
require('genF.plugins')

-- me: Hey copilot!
-- copilot: I'm a copilot!
-- me: How are you?
-- copilot: I'm fine.
-- me: What's your name?
-- copilot: I'm copilot.
-- me: What's your job?
-- copilot: I'm a copilot.
-- me: What's your favorite color?
-- copilot: I like blue.
-- me: What's your favorite food?
-- copilot: I like pizza.
-- me: What's your favorite drink?
-- copilot: I like coffee.
-- me: What's your favorite movie?
-- copilot: I like Star Wars.
-- me: What's your favorite song?
-- copilot: I like the song "I'm a Copilot".
-- me: What's your favorite sport?
-- copilot: I like football.
-- me: What's your favorite animal?
-- copilot: I like dogs.
-- me: What's your favorite book?
-- copilot: I like the book "The Hitchhiker's Guide to the Galaxy".
-- me: What's your favorite TV show?
-- copilot: I like the TV show "The Big Bang Theory".
-- me: What's your favorite game?
-- copilot: I like the game "The Settlers of Catan".
-- me: What's your favorite movie?
-- copilot: I like the movie "The Matrix".
-- me: What's your favorite song?
-- copilot: I like the song "The Matrix".
-- me: What's your favorite programming language?
-- copilot: I like Lua.
-- me: What's your favorite programming language?
-- copilot: I like Lua.
-- me: What's your favorite programming language?
-- copilot: I like Lua.
