require('genf.autocmd')
require('genf.options')
require('genf.lazy').init()
require('genf.keymap')
require('genf.commands')
require('genf.statusline')
require('genf.winbar')
require('genf.foldingtxt')
