# ┼───────────────────────────────────────────────────────────────────────────────────────┼
# │                                   « Lazy Plugins »                                    │
# ┼───────────────────────────────────────────────────────────────────────────────────────┼

[[plugins]] # Tagbar
repo = 'majutsushi/tagbar'

[[plugins]] # UndoTree
repo = 'mbbill/undotree'

[[plugins]] # Tabular
repo ='godlygeek/tabular' # << https://devhints.io/tabular

[[plugins]] # Vim Spector
repo = 'puremourning/vimspector'
marged = 0
hook_add = '''
let g:vimspector_enable_mappings = 'HUMAN'
'''

[[plugins]] # Colorizer
repo = 'lilydjwg/colorizer'
merged = 0
hook_add = '''
let g:colorizer_nomap=1
'''

#===================================================================================================
# FileType
#===================================================================================================
[[plugins]] # Csv
repo = "chrisbra/csv.vim"
on_ft = 'csv'

[[plugins]] # Goyo
repo = 'junegunn/goyo.vim'
on_ft = ['txt', 'md']

[[plugins]] # Toml
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']
depends = 'tagbar-markdown'
hook_add = '''
let g:vim_markdown_fenced_languages = ['c++=cpp', 'viml=vim', 'bash=sh', 'ini=dosini']
set conceallevel=1
let g:vim_markdown_math = 1
'''

[[plugins]] # Tagbar Extention For Morkdown
repo = 'lvht/tagbar-markdown'
[[plugins]] # Emmet
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]] # Latex
repo = 'vim-latex/vim-latex'
merged = 0
on_ft = 'tex'
hook_add = '''
let g:Tex_SmartKeyBS = 0
let g:Tex_SmartKeyQuote = 0
let g:Tex_SmartKeyDot = 0
let g:Imap_UsePlaceHolders = 0
let g:Tex_CompileRule_pdf = 'lualatex $* > /dev/null'
let g:Tex_CompileRule_dvi = 'lualatex $* > /dev/null'
'''

[[plugins]] # Vimtex
repo = 'lervag/vimtex'
on_ft = ['tex', 'markdown', 'md']
