#==================================================================================================
# Plugins
#===================================================================================================
[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]] # コメントアウトとか手軽にできるようになる。
repo = "tpope/vim-commentary"

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-surround'
merged = 0

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]] # gitをvimから使う
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'yggdroot/indentline'

##===================================================================================================
## Startify
##===================================================================================================
#[[plugins]]
#repo = 'mhinz/vim-startify'
#hook_add = '''
#function! s:nerdtreeBookmarks()
#    let bookmarks = systemlist("cut -d' ' -f 2- ~/.NERDTreeBookmarks")
#    let bookmarks = bookmarks[0:-2] " Slices an empty last line
#    return map(bookmarks, "{'line': v:val, 'path': v:val}")
#endfunction
#let g:startify_enable_special      = 1
#let g:startify_files_number        = 20
#let g:startify_relative_path       = 1
#let g:startify_change_to_dir       = 1
#let g:startify_update_oldfiles     = 1
#let g:startify_session_autoload    = 1
#let g:startify_session_persistence = 1
#let g:startify_skiplist = [
#        \ 'COMMIT_EDITMSG',
#        \ 'bundle/.*/doc',
#        \ '/data/repo/neovim/runtime/doc',
#        \ '/Users/mhi/local/vim/share/vim/vim74/doc',
#        \ ]
#let g:startify_bookmarks = [ ]
#let g:startify_custom_header = ['']
#let g:startify_custom_footer = ['', "", '']
#let g:startify_lists = [
#      \ { 'type': function('s:nerdtreeBookmarks'), 'header': ['   NERDTree Bookmarks']},
#      \ { 'type': 'files',     'header': ['   MRU']            },
#      \ { 'type': 'sessions',  'header': ['   Sessions']       },
#      \ { 'type': 'bookmarks', 'header': ['   Bookmarks']      },
#      \ { 'type': 'commands',  'header': ['   Commands']       },
#      \ ]
#" hi StartifyBracket ctermfg=240
#" hi StartifyFile    ctermfg=147
#" hi StartifyFooter  ctermfg=240
#" hi StartifyHeader  ctermfg=114
#" hi StartifyNumber  ctermfg=215
#" hi StartifyPath    ctermfg=245
#" hi StartifySlash   ctermfg=240
#" hi StartifySpecial ctermfg=240
#'''

#===================================================================================================
# Airline
#===================================================================================================
[[plugins]] # Airlineのテーマ
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # ステータスラインの装飾
repo = 'vim-airline/vim-airline'

#===================================================================================================
# Snippet
#===================================================================================================
[[plugins]]
repo = 'honza/vim-snippets'
merged = 0

#===================================================================================================
# Fern
#===================================================================================================
[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
depends = ['fzf', 'fern.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/fern-mapping-git.vim'

[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

#===================================================================================================
# FZF
#===================================================================================================
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
merged = 0
rev = 'release/rpc'
depends = ['fzf', 'fzf.vim']

[[plugins]]
repo = 'junegunn/fzf.vim'
merged = 0

[[plugins]]
repo = 'junegunn/fzf'
merged = 0
build = './install --all'

#===================================================================================================
# COC
#===================================================================================================
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
